# Site settings
# -------------

title: jekyll-webpack
description: >-
  A simple opinionated boilerplate for Jekyll.

# Page settings
url: ""
baseurl: ""
date_format: "%b %-d, %Y"
google_analytics: 'UA-XXXXXXXX-X'

# SEO settings
email: clement.moron@gmail.com
author: Clement Moron

# Navigation settings
# Add the pages you want to see in the navigation
navigation:
  - _pages/react.html

# Build settings
# --------------

# Default markdown parser
markdown: kramdown

# Make sure that pages don't end up behind weird urls like:`_pages/myPage.html`
collections:
  pages:
    output: true
    permalink: /:path

# Make sure the `_pages/` is processed
include:
  - _pages

# Make sure the `_site/assets/` is not trashed (webpack output)
keep_files:
  - assets

# List our Jekyll plugins below
plugins:
- jekyll-seo-tag

# Exclude from processing (not moved to `_site/`)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CNAME
  - LICENSE
  - README.md
  - webpack.config.js
  - "*.lock"
  - "*.log"
